name: .NET Core Desktop

on:
  push:
    tags:
      - 'v*'

jobs:

  build:
    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    env:
      Solution_Name: SinglePass.WPF.sln
      Project_Path: .\SinglePass.WPF\SinglePass.WPF.csproj
      
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
        
    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2
      
    # Restore the application to populate the obj folder with RuntimeIdentifiers
    - name: Restore
      run: |
       msbuild $env:Project_Path /t:Restore /p:Configuration=$env:Configuration
      env:
        Configuration: Release

    # Build the application to populate the bin folder
    - name: Build
      run: |
       msbuild $env:Project_Path /t:Publish /p:Configuration=$env:Configuration /p:RuntimeIdentifier=win-x64 /p:SelfContained=true /p:PublishReadyToRun=True /p:PublishSingleFile=true
      env:
        Configuration: Release
    
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build_result
        path: .\SinglePass.WPF\bin\Release\net7.0-windows\win-x64\publish\

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          # Optional, GitHub token, a Personal Access Token with `public_repo` scope if needed
          # Required, if the artifact is from a different repo
          # Required, if the repo is private a Personal Access Token with `repo` scope is needed
          #github_token: ${{secrets.GITHUB_TOKEN}}
          # Optional, workflow file name or ID
          # If not specified, will be inferred from run_id (if run_id is specified), or will be the current workflow
          #workflow: dotnet-desktop.yml
          # Optional, the status or conclusion of a completed workflow to search for
          # Can be one of a workflow conclusion:
          #   "failure", "success", "neutral", "cancelled", "skipped", "timed_out", "action_required"
          # Or a workflow status:
          #   "completed", "in_progress", "queued"
          # Use the empty string ("") to ignore status or conclusion in the search
          #workflow_conclusion: success
          # Optional, will get head commit SHA
          #pr: ${{github.event.pull_request.number}}
          # Optional, no need to specify if PR is
          #commit: ${{github.event.pull_request.head.sha}}
          # Optional, will use the specified branch. Defaults to all branches
          #branch: master
          # Optional, defaults to all types
          #event: push
          # Optional, will use specified workflow run
          #run_id: 1122334455
          # Optional, run number from the workflow
          #run_number: 34
          # Optional, uploaded artifact name,
          # will download all artifacts if not specified
          # and extract them into respective subdirectories
          # https://github.com/actions/download-artifact#download-all-artifacts
          #name: artifact_name
          # Optional, a directory where to extract artifact(s), defaults to the current directory
          path: ./artifacts/
          # Optional, defaults to current repo
          #repo: ${{ github.repository }}
          # Optional, check the workflow run to whether it has an artifact
          # then will get the last available artifact from the previous workflow
          # default false, just try to download from the last one
          check_artifacts:  false
          # Optional, search for the last workflow run whose stored an artifact named as in `name` input
          # default false
          search_artifacts: false
          # Optional, choose to skip unpacking the downloaded artifact(s)
          # default false
          skip_unpack: true
          # Optional, choose how to exit the action if no artifact is found
          # can be one of:
          #  "fail", "warn", "ignore"
          # default fail
          if_no_artifact_found: fail

      # - name: Create release
      #   uses: actions/create-release@v1
      #   id: create_release
      #   with:
      #     draft: false
      #     prerelease: false
      #     release_name: ${{ steps.version.outputs.version }}
      #     tag_name: ${{ github.ref }}
      #   env:
      #     GITHUB_TOKEN: ${{ github.token }}

      # Using script because we need to automate generate_release_notes
      - name: Create release
        uses: "actions/github-script@v6.4.0"
        env:
          RELEASE_NAME: ${{ steps.version.outputs.version }}
          TAG_NAME: ${{ github.ref }}
        with:
          script: |
            try {
              const response = await github.rest.repos.createRelease({
                draft: false,
                generate_release_notes: true,
                name: process.env.RELEASE_NAME,
                owner: context.repo.owner,
                prerelease: false,
                repo: context.repo.repo,
                tag_name: process.env.TAG_NAME,
              });
              core.exportVariable('RELEASE_ID', response.data.id);
              core.exportVariable('RELEASE_UPLOAD_URL', response.data.upload_url);
            } catch (error) {
              core.setFailed(error.message);
            }

      - name: Upload artifact
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ env.RELEASE_UPLOAD_URL }}
          asset_path: ./artifacts/build_result.zip
          asset_name: build_result.zip
          asset_content_type: application/zip