name: Build and create release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    env:
      SOLUTION_NAME: SinglePass.WPF.sln
      PROJECT_PATH: .\SinglePass.WPF\SinglePass.WPF.csproj
      CONFIGURATION: Release
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3.1
    - name: Restore
      run: |
       msbuild $env:PROJECT_PATH /t:Restore /p:Configuration=$env:CONFIGURATION
    - name: Build
      run: |
       msbuild $env:PROJECT_PATH /t:Publish /p:Configuration=$env:CONFIGURATION /p:RuntimeIdentifier=win-x64 /p:SelfContained=true /p:PublishReadyToRun=true /p:PublishSingleFile=true
    - name: Create .zip artifacts
      run: |
        Compress-Archive -Path '.\SinglePass.WPF\bin\Release\net7.0-windows\win-x64\publish\' -DestinationPath '.\SinglePass.WPF.zip'
    - name: Create release
      uses: "actions/github-script@v6.4.0"
      env:
        RELEASE_NAME: ${{ github.ref_name }}
        TAG_NAME: ${{ github.ref }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        script: |
          try {
            const response = await github.rest.repos.createRelease({
              draft: false,
              generate_release_notes: true,
              name: process.env.RELEASE_NAME,
              owner: context.repo.owner,
              prerelease: false,
              repo: context.repo.repo,
              tag_name: process.env.TAG_NAME,
            });
            core.exportVariable('RELEASE_ID', response.data.id);
            core.exportVariable('RELEASE_UPLOAD_URL', response.data.upload_url);
          } catch (error) {
            core.setFailed(error.message);
          }
    - name: Upload artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ env.RELEASE_UPLOAD_URL }}
        asset_path: .\SinglePass.WPF.zip
        asset_name: SinglePass.WPF.zip
        asset_content_type: application/zip

      # - name: Create release
      #   uses: actions/create-release@v1
      #   id: create_release
      #   with:
      #     draft: false
      #     prerelease: false
      #     release_name: ${{ steps.version.outputs.version }}
      #     tag_name: ${{ github.ref }}
      #   env:
      #     GITHUB_TOKEN: ${{ github.token }}